export const GET_POKEMON_DETAIL_REQUEST = 'GET_POKEMON_DETAIL_REQUEST';
export const GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMON_DETAIL_SUCCESS';
export const GET_POKEMON_DETAIL_FAILURE = 'GET_POKEMON_DETAIL_FAILURE';
